apiVersion: v1
kind: Service
metadata:
  name: {{ include "users-api-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "users-api-chart.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "users-api-chart.fullname" . }}
